name: Release

on:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[release v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set release version from commit message
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '\[release v\K[^\]]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      
      - name: Check if artifacts folder has entries
        id: check_artifacts
        run: |
          if [ -d "artifacts" ] && [ "$(ls -A artifacts)" ]; then
            echo "has_entries=true" >> $GITHUB_OUTPUT
          else
            echo "has_entries=false" >> $GITHUB_OUTPUT
          fi

      - name: Zip all artifacts
        if: steps.check_artifacts.outputs.has_entries == 'true'
        run: |
          cd artifacts
          for dir in */ ; do
            zip -r "${dir%/}.zip" "$dir"
          done

      - name: Create GitHub Release (without files)
        if: steps.check_artifacts.outputs.has_entries == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}

      - name: Create GitHub Release
        if: steps.check_artifacts.outputs.has_entries == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: artifacts/*.zip

      - name: Remove artifact directory
        run: rm -rf artifacts
